name: zz
on: 
  schedule: #每周日删除历史记录
    - cron: '0 0 * * 0'
  workflow_dispatch:

jobs:
  zz-job: 
    name: Delete History
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: init
      run: | 
         git config --local user.name "GitHub Actions"
         git config --local user.email "actions@github.com"
    - name: push main
      run: | 
         git checkout --orphan latest_branch
         git add -A
         git commit -am "Hello World"
         git branch -D main
         git branch -m main
         git push -f origin main
